name: RCConnect
main: de.raidcraft.connect.ConnectPlugin
version: ${project.version}#${build.number}
author: Dragonfire
website: www.raid-craft.de
depend: [RaidCraft-API]
database: true
api-version: 1.13